name: "Lint"

on:
  push:
    branches: [ main ]

jobs:

  build: 

    runs-on: ubuntu-latest

    container: registry.services.k8s.true.nl/library/helm-push:2.0.0
    
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
    
      - name: Run Lint
        run: |
          cd charts
          for i in `ls -d */ | cut -f1 -d'/'`
          do
            helm lint $i
          done
